/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    { type: 'doc', label: 'Intro', id: 'intro' },
    {
      type: 'category',
      label: 'Elementary',
      items: [
        { type: 'doc', label: 'Blockchain', id: 'elementary/blockchain' },
        { type: 'doc', label: 'Arweave', id: 'elementary/arweave' },
        {
          type: 'doc',
          label: 'Gateways',
          id: 'elementary/gateways',
        },
      ],
    },
    {
      type: 'category',
      label: 'PST',
      items: [
        { type: 'doc', label: 'Intro', id: 'pst/introduction/intro' },
        {
          type: 'category',
          label: 'Profit Sharing',
          items: [
            {
              type: 'doc',
              label: 'Profit Sharing Tokens',
              id: 'pst/profit-sharing/profit-sharing-tokens',
            },
            {
              type: 'doc',
              label: 'Profit Sharing Communities',
              id: 'pst/profit-sharing/profit-sharing-communities',
            },
          ],
        },
        {
          type: 'category',
          label: 'Writing PST contract',
          items: [
            {
              type: 'doc',
              label: 'Preparations',
              id: 'pst/writing-pst-contract/preparations',
            },
            {
              type: 'doc',
              label: 'Initial State',
              id: 'pst/writing-pst-contract/initial-state',
            },
            {
              type: 'doc',
              label: 'Contract Source',
              id: 'pst/writing-pst-contract/contract-source',
            },
          ],
        },
        {
          type: 'category',
          label: 'Writing tests',
          items: [
            {
              type: 'doc',
              label: 'Networks',
              id: 'pst/tests/networks',
            },
            {
              type: 'doc',
              label: 'Preparations',
              id: 'pst/tests/preparations',
            },
            {
              type: 'doc',
              label: 'Execution',
              id: 'pst/tests/execution',
            },
          ],
        },
        { type: 'doc', label: 'Deployment', id: 'pst/deployment/deployment' },
      ],
    },
  ],
};

module.exports = sidebars;
