/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    { type: 'doc', label: 'Intro', id: 'docs-intro' },
    {
      type: 'category',
      label: 'SDK',
      items: [
        { type: 'doc', label: 'Overview', id: 'sdk/overview' },
        { type: 'doc', label: 'SmartWeave protocol', id: 'sdk/smartweave-protocol' },
        { type: 'doc', label: 'Installation', id: 'sdk/installation' },
        { type: 'doc', label: 'WarpFactory', id: 'sdk/factory' },
        { type: 'doc', label: 'Bundled contract', id: 'sdk/bundled-contract' },
        { type: 'doc', label: 'Bundled interaction', id: 'sdk/bundled-interaction' },
        { type: 'doc', label: 'Deployment', id: 'sdk/deployment' },
        { type: 'doc', label: 'Register contract', id: 'sdk/register-contract' },
        { type: 'doc', label: 'Contract methods', id: 'sdk/contract-methods' },
        { type: 'doc', label: 'Evolve', id: 'sdk/evolve' },
        { type: 'doc', label: 'WASM', id: 'sdk/wasm' },
        { type: 'doc', label: 'VM2', id: 'sdk/vm2' },
        { type: 'doc', label: 'Internal calls', id: 'sdk/internal-calls' },
        { type: 'doc', label: 'Unsafe client', id: 'sdk/unsafe-client' },
        { type: 'doc', label: 'Cache', id: 'sdk/cache' },
        { type: 'doc', label: 'SmartWeave Global API', id: 'sdk/smartweave-global' },
      ],
    },
    {
      type: 'category',
      label: 'Warp Gateway',
      items: [{ type: 'doc', label: 'Overview', id: 'gateway/overview' }],
    },
    { type: 'doc', label: 'CLI', id: 'cli/installation' },
    {
      type: 'category',
      label: 'Warp D.R.E.',
      items: [{ type: 'doc', label: 'Overview', id: 'dre/overview' }],
    },
    {
      type: 'category',
      label: 'Warp Plugins',
      items: [{ type: 'doc', label: 'Overview', id: 'plugins/overview' }],
    },
    // { type: 'doc', label: 'Evolve', id: 'evolve' },
    // { type: 'doc', label: 'Internal calls', id: 'internal-calls' },
    // { type: 'doc', label: 'VRF', id: 'vrf' },
    // { type: 'doc', label: 'SmartWeave Global', id: 'smartweave-global' },
  ],
};

module.exports = sidebars;
