/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    { type: 'doc', label: 'Intro', id: 'docs-intro' },
    {
      type: 'category',
      label: 'SDK',
      items: [{ type: 'doc', label: 'Overview', id: 'sdk/overview' }],
    },
    {
      type: 'category',
      label: 'Warp Gateway',
      items: [{ type: 'doc', label: 'Overview', id: 'gateway/overview' }],
    },
    {
      type: 'category',
      label: 'Warp D.R.E.',
      items: [{ type: 'doc', label: 'Overview', id: 'dre/overview' }],
    },
    {
      type: 'category',
      label: 'Warp Plugins',
      items: [{ type: 'doc', label: 'Overview', id: 'plugins/overview' }],
    },
    // { type: 'doc', label: 'Evolve', id: 'evolve' },
    // { type: 'doc', label: 'Internal calls', id: 'internal-calls' },
    // { type: 'doc', label: 'VRF', id: 'vrf' },
    // { type: 'doc', label: 'SmartWeave Global', id: 'smartweave-global' },
  ],
};

module.exports = sidebars;
