/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // But you can create a sidebar manually

    standardsSidebar: [
        {
            type: 'doc',
            label: 'Intro',
            id: 'standards-intro',
        },
        {
            type: 'category',
            label: 'Atomic asset',
            items: [
                {
                    type: 'doc',
                    label: 'Atomic-asset',
                    id: 'atomic-asset',
                },
                {
                    type: 'doc',
                    label: 'Tradeable',
                    id: 'tradeable',
                },
                {
                    type: 'doc',
                    label: 'Implementation',
                    id: 'tradeable-atomic-asset',
                },
            ],
        },
        {
            type: 'category',
            label: 'Atomic Asset (Jim & Atticus)',
            items: [
                {
                    type: 'doc',
                    label: 'Atomic Asset Interface',
                    id: 'standards-jim-atticus/atomic-asset-interface'
                },
                {
                    type: 'doc',
                    label: 'Atomic Token Interface',
                    id: 'standards-jim-atticus/atomic-token-interface'
                },
                {
                    type: 'doc',
                    label: 'Composability & Inheritance',
                    id: 'standards-jim-atticus/composability-and-inheritance'
                }
            ]
        }
    ]
};


module.exports = sidebars;
